name: Upload Test Report

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests with coverage
        run: node --experimental-vm-modules node_modules/jest/bin/jest.js --coverage --coverageDirectory=coverage

      - name: Check coverage output
        run: ls -R coverage || echo "no coverage generated"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/**